Using NameSpace System.Management.Automation.Runspaces
Using NameSpace System.IO
Using NameSpace System.Security
<#
    This is an AD Config module for use with DryDeploy, or by itself.
    Copyright (C) 2021  Bjørn Henrik Formo (bjornhenrikformo@gmail.com)
    LICENSE: https://raw.githubusercontent.com/bjoernf73/dry.module.ad/main/LICENSE
#>
function New-DryADUser{
    [CmdletBinding(DefaultParameterSetName = 'Local')]
    param(
        [Parameter(Mandatory, HelpMessage = "User Object Specification")]
        [ValidateNotNullOrEmpty()]
        [PSObject]
        $User,

        [Parameter(Mandatory, HelpMessage = "NetBIOS domain name")]
        [string]
        $DomainNB,

        [Parameter(Mandatory, ParameterSetName = 'Remote',
            HelpMessage = "PSSession to run the script blocks in")]
        [PSSession]
        $PSSession,

        [Parameter(Mandatory, ParameterSetName = 'Local',
            HelpMessage = "For 'Local' sessions, specify the Domain Controller to use")]
        [string]
        $DomainController,

        [Parameter(Mandatory, ParameterSetName = 'Remote',
            HelpMessage = "Path to the Domain Controller's Web Certificate ('Server
        Authentication') Public Certificate file.
        Used in Remote execution to encrypt users's password")]
        [FileInfo]
        $DCPublicCertificateFilePath,

        [Parameter(HelpMessage = "Should only be `$true when called from DryDeploy. Will allow autogenerated
        passwords for users that are created to be stored in DryDeploy's Credentials store. If you're running
        standalone (not as part of DryDeploy, hence `$DryDeploy = `$false), then passwords are autogenerated,
        but lost. You will have to reset the passwords of the created users to access those accounts")]
        [Switch]$DryDeploy
    )

    # Test if object exists. Currently does not test properties, only if it exists or not
    try{
        if($PSCmdlet.ParameterSetName -eq 'Remote'){
            $Server = 'localhost'
            $ExecutionType = 'Remote'
            olad v @('Session Type', 'Remote')
            olad v @('Remoting to Domain Controller', $PSSession.ComputerName)
        }
        else{
            $Server = $DomainController
            $ExecutionType = 'Local'
            olad v @('Session Type', 'Local')
            olad v @('Using Domain Controller', $Server)
        }

        $GetArgumentList = @(
            $User.Name,
            $Server
        )
        $InvokeGetParams = @{
            ScriptBlock  = $DryAD_SB_User_Get
            ArgumentList = $GetArgumentList
        }
        if($PSCmdlet.ParameterSetName -eq 'Remote'){
            $InvokeGetParams += @{
                Session = $PSSession
            }
        }
        $GetResult = Invoke-Command @InvokeGetParams

        switch($GetResult){
            $true{
                olad v @('The User exists already', "$($User.Name)")
            }
            $false{
                olad v @('The user does not exist', "$($User.Name)")
            }
            default{
                olad e @('Error trying to get user', "$($User.Name)")
                throw $GetResult
            }
        }

        if($GetResult -eq $false){

            # If $User.Enabled not specified, enable the account
            if($null -eq $User.Enabled){
                $User | Add-Member -MemberType 'NoteProperty' -Name 'Enabled' -Value $true
            }

            # Create a hash to splat to new-aduser
            $UserSpec = @{}
            $ExcludeProperties = @(
                'alias',
                'memberof',
                'password'
            )
            $User.PSObject.Properties | foreach-Object{
                if($_.Name -notin $ExcludeProperties){
                    $UserSpec += @{$_.Name = $_.Value }
                }
            }

            $GetDryADCredentialParams = @{
                UserName = "$DomainNB\$($User.Name)"
            }
            if($User.password.get_or_generate -eq 'generate'){
                $GetDryADCredentialParams += @{
                    Random = $true
                }
                if($User.password.length){
                    $GetDryADCredentialParams += @{
                        Length = [int]$User.password.length
                    }
                }
                if($User.password.nonalphabetics){
                    $GetDryADCredentialParams += @{
                        NonAlphabetics = [int]$User.password.nonalphabetics
                    }
                }

                [PSCredential]$UserCredential = Get-DryADCredential @GetDryADCredentialParams

                if($DryDeploy){
                    # This sessions is running from DryDeploy - so add to DryDeploy Credential Store
                    Add-DryCredential -Alias $User.Name -Credential $UserCredential
                }
            }
            else{
                if($DryDeploy){
                    # Using function from DryDeploy to get Credential from it's Credential's Store
                    [PSCredential]$UserCredential = Get-DryCredential -Alias $User.Name -EnvConfig $GLOBAL:dry_var_global_ConfigCombo.envconfig.name
                }
                else{
                    # Invoking an interactive prompt
                    [PSCredential]$UserCredential = Get-DryADCredential @GetDryADCredentialParams
                }
            }

            switch($ExecutionType){
                'Remote'{
                    # If remote execution, we must send the password over the network.
                    # If so, make sure the password is encrypted with the target Domain
                    # Controller's Server Certificate
                    $ConvertPwdParams = @{
                        ClearText       = $UserCredential.GetNetworkCredential().Password
                        CertificateFile = $DCPublicCertificateFilePath
                    }
                    $Base64EncodedPass = Convert-DryADClearTextToEncryptedString @ConvertPwdParams
                    olad v @("Encrypted password for $($User.Name)", "$Base64EncodedPass")
                }
                'Local'{
                    # If local execution, we must send the password to Invoke-Command.
                    # It is good practise to use SecureString, which ensures that only
                    # the local system may decrypt it, so if it is accidentally sent
                    # over a PSSession to a remote system, it is unusable
                    [SecureString]$SecureString = $UserCredential.Password
                }
                default{
                    throw "Unknown ExecutionType: $ExecutionType"
                }
            }

            $SetArgumentList = @(
                $UserSpec,
                $ExecutionType,
                $Server
            )
            switch($ExecutionType){
                'Remote'{
                    $SetArgumentList += $Base64EncodedPass
                }
                'Local'{
                    $SetArgumentList += $SecureString
                }
            }

            $InvokeSetParams = @{
                ScriptBlock  = $DryAD_SB_User_Set
                ArgumentList = $SetArgumentList
            }
            switch($ExecutionType){
                'Remote'{
                    $InvokeSetParams += @{
                        Session = $PSSession
                    }
                }
                default{
                }
            }
            $SetResult = Invoke-Command @InvokeSetParams

            if($SetResult[0] -eq $true){
                olad v @('Successfully created user', "$($User.Name)")
            }
            else{
                olad e "Error creating user $($User.Name): $($SetResult[1])"
                throw "$($SetResult[1])"
            }
        }
    }
    catch{
        $PSCmdlet.ThrowTerminatingError($_)
    }
}
